# Generated by Django 4.2.4 on 2023-08-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('song', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'title',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RingTone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.FileField(upload_to='')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.date')),
            ],
        ),
    ]
