# Generated by Django 4.2.4 on 2023-08-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ringtone_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringtone',
            name='time',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
